"use client";

import { useEffect, useMemo, useState } from "react";
import { useI18n } from "../../components/I18nProvider";
import { normalizeEvent } from "../../lib/api";
import type { EventView } from "../../lib/demo-data";
import { apiRequest, errorMessage } from "../../lib/client-api";
import { StudioNav } from "../StudioNav";

export function StudioInsightsClient() {
  const { locale, t } = useI18n(); const [items, setItems] = useState<EventView[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { apiRequest<{ items: Array<Partial<EventView> & Pick<EventView, "id" | "publicSlug" | "title">> }>("/me/hosted-events", { authenticated: true }).then((payload) => setItems(payload.items.map(normalizeEvent))).catch((error) => setMessage(errorMessage(error))).finally(() => setLoading(false)); }, []);
  const metrics = useMemo(() => { const completed = items.filter((item) => item.status === "ended"); const totalSeats = items.reduce((sum, item) => sum + item.capacity, 0); const confirmed = items.reduce((sum, item) => sum + item.confirmedCount, 0); return { events: items.length, completed: completed.length, confirmed, fill: totalSeats ? Math.round(confirmed / totalSeats * 100) : 0, categories: Object.entries(items.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.categoryLabel]: (counts[item.categoryLabel] ?? 0) + item.confirmedCount }), {})).sort((a, b) => b[1] - a[1]) }; }, [items]);
  const copy = locale === "ja" ? { title: "データと振り返り", body: "実際のイベントと申込データだけを集計しています。", events: "イベント", completed: "完了", confirmed: "確定申込", fill: "平均充足率", mix: "カテゴリー別申込", no: "集計できるデータはまだありません" } : locale === "en" ? { title: "Insights", body: "Calculated only from your real events and registration data.", events: "Events", completed: "Completed", confirmed: "Confirmed", fill: "Average fill", mix: "Registrations by category", no: "No data to summarize yet" } : { title: "数据复盘", body: "只根据你的真实活动与报名数据计算，不展示模拟指标。", events: "活动总数", completed: "已完成", confirmed: "确认报名", fill: "平均满座率", mix: "分类报名分布", no: "暂时没有可以复盘的数据" };
  return <main className="studio-shell"><StudioNav current="insights" /><section className="studio-content"><div className="dashboard-heading"><div><span className="section-number">HOST STUDIO / INSIGHTS</span><h1>{copy.title}</h1><p>{copy.body}</p></div></div>{message && <p className="form-message">{message}</p>}{loading ? <div className="loading-state"><span /><p>{t("common.loading")}</p></div> : items.length ? <><div className="metric-grid insight-metrics"><div><span>{copy.events}</span><strong>{metrics.events}</strong></div><div><span>{copy.completed}</span><strong>{metrics.completed}</strong></div><div><span>{copy.confirmed}</span><strong>{metrics.confirmed}</strong></div><div><span>{copy.fill}</span><strong>{metrics.fill}%</strong></div></div><section className="insight-breakdown"><div className="section-heading"><div><span className="section-number">AUDIENCE</span><h2>{copy.mix}</h2></div></div>{metrics.categories.map(([category, count]) => <div className="insight-bar" key={category}><span>{category}</span><i><b style={{ width: `${metrics.confirmed ? Math.max(3, count / metrics.confirmed * 100) : 0}%` }} /></i><strong>{count}</strong></div>)}</section></> : <div className="empty-state compact-empty"><h2>{copy.no}</h2></div>}</section></main>;
}
